include .envrc

# ==================================================================================== #
# HELPERS
# ==================================================================================== #

## help: print this help message
.PHONY: help
help:
	@echo 'Usage:'
	@sed -n 's/^##//p' ${MAKEFILE_LIST} | column -t -s ':' |  sed -e 's/^/ /'

.PHONY: confirm
confirm:
	@echo -n 'Are you sure? [y/N] ' && read ans && [ $${ans:-N} = y ]

# ==================================================================================== #
# DEVELOPMENT
# ==================================================================================== #

## run/api: run the cmd/api application
.PHONY: run/api
run/api:
	go run ./cmd/api -db-dsn={{printf "${%s_DB_DSN}" .envProjectName }}

## db/psql: connect to the database using psql
.PHONY: db/psql
db/psql:
	psql {{printf "${%s_DB_DSN}" .envProjectName }}

## db/migrations/new name=$1: create a new database migration
.PHONY: db-m-new
db-m-new:
	@echo 'Creating migration files for ${name}...'
	goose -dir='./migrations' create {{"${name}"}} sql

## db/migrations/up: apply all up database migrations
.PHONY: db-m-up
db-m-up: confirm
	@echo 'Running up migrations...'
	goose up

# ==================================================================================== #
# QUALITY CONTROL
# ==================================================================================== #

## tidy: format all .go files, and tidy and vendor module dependencies
.PHONY: tidy
tidy:
	@echo 'Tidying module dependencies...'
	go mod tidy
	@echo 'Verifying and vendoring module dependencies...'
	go mod verify
	go mod vendor
	@echo 'Formatting .go files...'
	go fmt ./...

## audit: run quality control checks
.PHONY: audit
audit:
	@echo 'Checking module dependencies...'
	go mod tidy -diff
	go mod verify
	@echo 'Vetting code...'
	go vet ./...
	go tool staticcheck ./...
	@echo 'Running tests...'
	go test -race -vet=off ./...

# ==================================================================================== #
# BUILD
# ==================================================================================== #

## build/api: build the cmd/api application
.PHONY: build/api
build/api:
	@echo 'Building cmd/api...'
	go build -ldflags="-s" -o=./bin/api ./cmd/api
	GOOS=linux GOARCH=amd64 go build -ldflags="-s" -o=./bin/linux_amd64/api ./cmd/api

# ==================================================================================== #
# PRODUCTION
# ==================================================================================== #

production_host_ip = "your.ip.address"

## production/connect: connect to the production server
.PHONY: production/connect
production/connect:
	ssh {{.projectName}}@{{"${production_host_ip}"}}

## production/deploy/api: deploy the api to production
.PHONY: production/deploy/api
production/deploy/api:
	rsync -P ./bin/linux_amd64/api {{.projectName}}@{{"${production_host_ip}"}}:~
	rsync -rP --delete ./migrations {{.projectName}}@{{"${production_host_ip}"}}:~
	rsync -P ./remote/production/api.service {{.projectName}}@{{"${production_host_ip}"}}:~
	rsync -P ./remote/production/Caddyfile {{.projectName}}@{{"${production_host_ip}"}}:~
	ssh -t {{.projectName}}@{{"${production_host_ip}"}} '\
		goose up \
		&& sudo mv ~/api.service /etc/systemd/system/ \
		&& sudo systemctl enable api \
		&& sudo systemctl restart api \
		&& sudo mv ~/Caddyfile /etc/caddy/ \
		&& sudo systemctl reload caddy \
	'

.PHONY: openapi-generate
openapi-generate:
	go generate ./...
